# Generated by Django 4.1 on 2022-10-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='contenido',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='titulo',
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tienda'),
        ),
    ]
