# Generated by Django 4.1 on 2022-10-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_productos_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoriaProd', 'verbose_name_plural': 'categoriasProd'},
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categorias',
        ),
        migrations.AddField(
            model_name='productos',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
