# Generated by Django 4.1 on 2022-10-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_categoria_options_remove_productos_categorias_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaProd',
        ),
    ]
