# Generated by Django 4.1 on 2022-10-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_productos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
