# Generated by Django 4.1 on 2022-10-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicios_delete_servicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
