# Generated by Django 4.1 on 2022-10-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_rename_servicios_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='Contenido',
            new_name='contenido',
        ),
    ]
