# Generated by Django 4.1 on 2022-10-05 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebJecApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
